### ISSUE TITLE
MQTT username and password

### ISSUE THREAD

**Issue by hawaltie** [DiederikvandenB/nad-controller#1]
In the first place: thank you for puitting your effort in this software. I am the proud owner of a NAD C390DD, and I want to use home assistant to control the NAD device. I currently use Mosquito with username and password. Can I also us a MQTT username and password in your setup?

**Comment by DiederikvandenB** [comment]
Yeah that should be possible without too much effort.

I think it's currently best if you fork the repo and start fiddling around a bit with it, before I start making changes to this repo. I have no idea how well this code will (or will not) work for other amps, but maybe later on we can merge some things.

You'll want to start [here](https://github.com/DiederikvandenB/nad-controller/blob/master/main.go#L76) by implementing [SetUsername](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetUsername) and [SetPassword](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions).

**Comment by hawaltie** [comment]
If I was a programmer, I could do this, however I am not.

**Comment by DiederikvandenB** [comment]
In that case I’m afraid this software isn’t what you are looking for. It’s not at the level of being ready for plug and play as it will probably require changes specific to your setup.
